### PR TITLE
version 2.0.7 of oauth adjustment

### PR DESCRIPTION
**Pull request by mariubog**
version OAuth 2.0.7  seems to need to have `UserDetailsService` set with `AuthorizationServerEndpointsConfigurer` in order for refresh_token to work properly.

### CODE REVIEW

**Comment by mariubog** [comment]
there were some minor errors in first commit (one dot to many) I fixed it above and it shows no errors now

**Comment by royclarkson** [comment]
Thanks for the PR! Would you mind squashing the commits?

**Comment by mariubog** [comment]
I would not mind but I am not sure how to do that I wanted to delete the previous ones that contained errors but did not how  . If you want to change them somehow I am fine with that otherwise if there is something I can do  to squash them, could you explain briefly how to do that? I cant use my github client at the moment so I am doing it just editing plain text. Sorry about that.

**Comment by royclarkson** [comment]
I usually do a `git reset --soft HEAD~3` where 3 is the number of commits to go back to. Or you can specify a specific commit, like `git reset --soft f4d66d4e24b9de8de348d4f1e9bc5c02e52ed59d`. That will remove the multiple commits but keep all your changes. Then you can create a single, new commit.

**Comment by mariubog** [comment]
thanks , I ll work on it tonight and post less messy pull request.

**Comment by mariubog** [comment]
I have done it and then I had to force push because I was behind but I think something is wrong and don't know why, If you look on the compare view of my commit and your master, it shows that my commit applies changes that are already done in your repo like changing versions in pom or gradle from old ones to newer ones, the issue is that in your repo they are already changed to new ones and are not supposed to be listed as changes. I do not know what I am doing wrong , if you have a couple of minutes could you look at it and maybe suggest something because this commit looks like it is doing more than it really does. I only changes maybe couple of lines of code, no more than 10 probably.


 Anyway I also changed roles and normalized it to ManyTomany relationship.

**Comment by mariubog** [comment]
I had to many problems so I closed this one and created new fresh one that seems to be ok here: 
https://github.com/royclarkson/spring-rest-service-oauth/pull/21

**Pull request closed without merging**
